import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import classNames from "classnames";


export default function Home() {
  const [open, setOpen] = useState(false);
  const dices = ["calabash", "crab", "deer", "fish", "rooster", "shrimp"];

  const getRandomList = () => {
    return dices.sort(() => 0.5 - Math.random()).slice(0, 3);
  };

  const [randomList, setRandomList] = useState(getRandomList());
  const [vibrate, setVibrate] = useState(false);

  console.log(randomList);

  const handleRoll = () => {
    setVibrate(true);
    play();
    setTimeout(() => {
      setVibrate(false);
      setRandomList(getRandomList());
    }, 4000);
  };

  function play() {
    var audio = document.getElementById("a1");
    audio.play();
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={'main'}>
        <div className={classNames("bau_cua_wrapper", { open: open })}>
          <Image
            // className={"dia_co_tien"}
            className={classNames("dia_co_tien", { shake: vibrate })}
            src="/dia-co-tien.png"
            alt="Dia co tien"
            width={500}
            height={500}
            priority
          />
          <div className="dice-result-wrapper">
            {randomList.map((item) => {
              return (
                <Image
                  className={"result-dice"}
                  src={"/tomcuaca/" + item + ".svg"}
                  alt="Result"
                  width={100}
                  height={100}
                  priority
                />
              );
            })}
          </div>
          <Image
            className={classNames("bat_sat", { shake: vibrate })}
            src="/bat-su.png"
            alt="Bat sat"
            width={400}
            height={400}
            priority
          />
        </div>
        <button onClick={() => setOpen(!open)}>{!open ? "Mở" : "Đóng"}</button>
        <button onClick={handleRoll}>Xóc</button>
        <audio id="a1" src="/shake-dice.mp3" />
      </main>
    </>
  );
}
